"""add token_count to articles

Revision ID: 04bc4081ddab
Revises: f816beef15d3
Create Date: 2026-04-28 20:49:24.200432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04bc4081ddab'
down_revision: Union[str, Sequence[str], None] = 'f816beef15d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('token_count', sa.Integer(), nullable=True))
    op.drop_column('articles', 'content')
    op.drop_column('articles', 'source')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('articles', 'token_count')
    # ### end Alembic commands ###
