"""add rss feed sources

Revision ID: 2dd2bdf1369f
Revises: 3f4e33bae1fd
Create Date: 2026-05-16 17:27:40.068023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dd2bdf1369f'
down_revision: Union[str, Sequence[str], None] = '3f4e33bae1fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rss_feed_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rss_feed_sources_id'), 'rss_feed_sources', ['id'], unique=False)
    op.create_index(op.f('ix_rss_feed_sources_url'), 'rss_feed_sources', ['url'], unique=True)
    op.drop_index(op.f('ix_articles_search_vector_gin'), table_name='articles', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_articles_search_vector_gin'), 'articles', ['search_vector'], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_rss_feed_sources_url'), table_name='rss_feed_sources')
    op.drop_index(op.f('ix_rss_feed_sources_id'), table_name='rss_feed_sources')
    op.drop_table('rss_feed_sources')
    # ### end Alembic commands ###
