"""add quality_score to articles

Revision ID: 31efc9813377
Revises: d4fc85cd0acd
Create Date: 2026-04-29 15:00:14.446671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31efc9813377'
down_revision: Union[str, Sequence[str], None] = 'd4fc85cd0acd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('quality_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'quality_score')
    # ### end Alembic commands ###
