"""add normalized_title to articles

Revision ID: 8fa235e3e0d5
Revises: 3da432f28370
Create Date: 2026-04-29 09:36:22.916091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fa235e3e0d5'
down_revision: Union[str, Sequence[str], None] = '3da432f28370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('normalized_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'normalized_title')
    # ### end Alembic commands ###
