"""add keywords to article

Revision ID: 9233d2e75013
Revises: 04bc4081ddab
Create Date: 2026-04-28 23:02:41.517540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9233d2e75013'
down_revision: Union[str, Sequence[str], None] = '04bc4081ddab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('keywords', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'keywords')
    # ### end Alembic commands ###
