"""add summary_hash to articles

Revision ID: 9785239653db
Revises: 8fa235e3e0d5
Create Date: 2026-04-29 09:51:37.416911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9785239653db'
down_revision: Union[str, Sequence[str], None] = '8fa235e3e0d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('summary_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'summary_hash')
    # ### end Alembic commands ###
