"""add summary to articles

Revision ID: b8ec71787004
Revises: 768c9983037c
Create Date: 2026-04-28 01:40:22.494050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8ec71787004'
down_revision: Union[str, Sequence[str], None] = '768c9983037c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'summary')
    # ### end Alembic commands ###
