"""add ingested_at to articles

Revision ID: d4fc85cd0acd
Revises: da2495df36f2
Create Date: 2026-04-29 14:24:12.546123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4fc85cd0acd'
down_revision: Union[str, Sequence[str], None] = 'da2495df36f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('ingested_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'ingested_at')
    # ### end Alembic commands ###
